### ISSUE TITLE
Relevancy: Remove days in the past from visibility during week of SXSW

### ISSUE THREAD

**Issue by willstokes** [mathewantony31/sxdiscover#17]
Update to display only current & future dates, so that people aren’t getting 2-day-old results when checking it during the week

**Comment by mathewantony31** [comment]
@willstokes, question: do you think people will care to see shows they went to? Almost like a historical record? One thing we could do is display the current day's results (or the nearest day in the future). That way you can still navigate back to previous days if you want

**Comment by mathewantony31** [comment]
have a diff ready. will test tomorrow by creating a fake show on March 1 and see if it jumps to the second day

**Comment by mathewantony31** [comment]
fixed! with https://github.com/mathewantony31/sxdiscover/pull/48
