### ISSUE TITLE
Update copy in Spotify auth page

### ISSUE THREAD

**Issue by mathewantony31** [mathewantony31/sxdiscover#44]

**Comment by willstokes** [comment]
doing this

**Comment by mathewantony31** [comment]
The "SX week in ATX" reads a bit weird. How about something like:
> giving you and your friends the perfect game plan to see your favorite bands.

**Comment by willstokes** [comment]
# Approved copy
SXDiscover matches your top artists & saved playlists on Spotify with all the bands playing SXSW - giving you and your friends the perfect game plan to see your favorite bands.

**Comment by willstokes** [comment]
done
