### ISSUE TITLE
scraper improvements

### ISSUE THREAD

**Issue by willstokes** [mathewantony31/sxdiscover#8]
- handle and preserve accent characters for matching (i.e. aminé)
- handle and preserve special characters for matching (i.e. ty dolla $ign)
....tbd

**Comment by mathewantony31** [comment]
changes made today:
- encoding in UTF-8 so it properly handles special characters
- added BeautifulSoup package to convert HTML entities to UTF (&amp; -> &)

running scraper tonight to see if the results look good!

**Comment by mathewantony31** [comment]
Done! Instructions added to Dropbox > SXDiscover > 2018 > scraper
